version: "3"
services:
  website:
    image: nginx
    ports:
      - "1884:80"
    restart: always
  
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      # - /netwerk1/mosquitto:/mosquitto
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - mosquitto
    ports:
      - 1883:1883

networks:
  mosquitto:
    name: mosquitto
    driver: bridge
